---

# Role for the node
encore::role: "role::base"

# NTP
encore::ntp::servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org

# SNMP
encore::snmp::contact: root@maludy.home
encore::snmp::location: Cincinnati, OH, USA, Earth, Milky Way
encore::snmp::ro_community: myPassword
encore::snmp::ro_network: 192.168.0.0/16

# MOTD (message of the day)
#  Leave the content empty (aka undef, nil) so that the puppetlabs/motd
#  module auto generates a motd.
encore::motd::content:

