---

# Role for the node
encore::role: "role::base"

# NTP
encore::ntp::servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

# SNMP
encore::snmp::contact: snmp@encore.tech
encore::snmp::location: Cincinnati, OH, USA
encore::snmp::ro_community: myPassword
encore::snmp::ro_network: 172.16.0.0/16

# MOTD (message of the day)
#  Leave the content empty (aka undef, nil) so that the puppetlabs/motd
#  module auto generates a motd.
encore::motd::content:

# MCollective
encore::mcollective::middleware_hosts:
  - puppetmco.maludy.home
